//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _028 {
            get {
                object obj = ResourceManager.GetObject("_028", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _1436 {
            get {
                object obj = ResourceManager.GetObject("_1436", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _2006_2_032_043_ {
            get {
                object obj = ResourceManager.GetObject("_2006_2_032_043_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _30446_165903520 {
            get {
                object obj = ResourceManager.GetObject("_30446_165903520", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _4709 {
            get {
                object obj = ResourceManager.GetObject("_4709", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _637 {
            get {
                object obj = ResourceManager.GetObject("_637", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _7_норм_док_кодекс_рб_об_образов {
            get {
                object obj = ResourceManager.GetObject("_7_норм_док_кодекс_рб_об_образов", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _748 {
            get {
                object obj = ResourceManager.GetObject("_748", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _814 {
            get {
                object obj = ResourceManager.GetObject("_814", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] _840 {
            get {
                object obj = ResourceManager.GetObject("_840", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] by028ru {
            get {
                object obj = ResourceManager.GetObject("by028ru", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] by029ru {
            get {
                object obj = ResourceManager.GetObject("by029ru", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] C21700710_1506546000 {
            get {
                object obj = ResourceManager.GetObject("C21700710_1506546000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] code_on_education_243_3_13_01_2011_ed_2012 {
            get {
                object obj = ResourceManager.GetObject("code_on_education_243_3_13_01_2011_ed_2012", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] dekret_prezidenta_respubliki_belarus_24_noyabrya_2006_g_n_18 {
            get {
                object obj = ResourceManager.GetObject("dekret_prezidenta_respubliki_belarus_24_noyabrya_2006_g_n_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] grazhdanskiy_processualnyy_kodeks {
            get {
                object obj = ResourceManager.GetObject("grazhdanskiy_processualnyy_kodeks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] kodeks_respubliki_belarus_o_brake_i_seme {
            get {
                object obj = ResourceManager.GetObject("kodeks_respubliki_belarus_o_brake_i_seme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] konstytutsyya_respublyky_belarus {
            get {
                object obj = ResourceManager.GetObject("konstytutsyya_respublyky_belarus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Socialnyi_pedagog_v_shkole_objazannosti_i_rol_v_uchrezhdenii1 {
            get {
                object obj = ResourceManager.GetObject("Socialnyi_pedagog_v_shkole_objazannosti_i_rol_v_uchrezhdenii1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Trudovoj_kodeks_RB {
            get {
                object obj = ResourceManager.GetObject("Trudovoj_kodeks_RB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ugolovno_processualnyy_kodeks {
            get {
                object obj = ResourceManager.GetObject("ugolovno_processualnyy_kodeks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ugolovno_yspolnytelnyj_kodeks_respublyky_belarus {
            get {
                object obj = ResourceManager.GetObject("ugolovno_yspolnytelnyj_kodeks_respublyky_belarus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WebResource {
            get {
                object obj = ResourceManager.GetObject("WebResource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Zakon_2435_XII {
            get {
                object obj = ResourceManager.GetObject("Zakon_2435_XII", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] zakon_o_pravah_rebenka {
            get {
                object obj = ResourceManager.GetObject("zakon_o_pravah_rebenka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] zakon_RB_200_prof_beznadzornosti {
            get {
                object obj = ResourceManager.GetObject("zakon_RB_200_prof_beznadzornosti", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Zakon_Respubliki_Belarus_OB_OSNOVAH_GOSUDARSTVENNOJ_MOLODEZHNOJ_POLITIKI {
            get {
                object obj = ResourceManager.GetObject("Zakon_Respubliki_Belarus_OB_OSNOVAH_GOSUDARSTVENNOJ_MOLODEZHNOJ_POLITIKI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Закона_РБ_об_образовании {
            get {
                object obj = ResourceManager.GetObject("Закона_РБ_об_образовании", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
